name: prototipo1precadastro
description: Primeiro prototipo do pre cadastro

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.0
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.5
  modal_progress_hud: ^0.1.3
#  flutter_secure_storage: ^3.3.2
  provider: ^4.0.5
  image_picker: ^0.6.5
  uuid: ^2.0.4
  image: ^2.1.12
  flutter_local_notifications: ^1.4.1
  intl: ^0.16.1
  mask_text_input_formatter: ^1.0.6
  path_provider: ^1.6.5
  firebase_messaging: ^6.0.13

  cupertino_icons: ^0.1.2

dev_dependencies:
#  flutter_test:
#    sdk: flutter


flutter:
  uses-material-design: true
